name: id-token test

permissions:
  contents: write
  id-token: write

on:
  push:

jobs:
  test-ok:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/github-script@v7
      id: my-script
      with:
        result-encoding: string
        retries: 3
        script: |
          var a = core.getIDToken("this-is-test-audience")
          core.info(a)
