
name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    container: ubuntu:20.04
    steps:
      - run: apt-get update
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/a
