name: test

on:
  workflow_dispatch:
  #push:
  #pull_request:

jobs:
  inside-host:

    strategy:
      matrix:
        v: [3.10.7, 3.9.14]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: check aws connection
        run: curl -v secretsmanager.ap-northeast-1.amazonaws.com

      - run: |
          docker pull alpine/git
          docker images

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.v }}

      - name: Python version check
        run: |
          python --version
          if python --version | grep "${{ matrix.v }}"; then echo "OK"; else echo "NOK"; exit 1; fi

  inside-container:

    strategy:
      matrix:
        v: [3.10.7, 3.9.14]

    runs-on: ubuntu-latest
    container:
      image: cimg/node:14.15.4
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.v }}

      - name: Python version check
        run: |
          python --version
          if python --version | grep "${{ matrix.v }}"; then echo "OK"; else echo "NOK"; exit 1; fi
