name: 066 Node12 deprecation

on:
  workflow_dispatch:

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1


  cibtauber:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: --user root

    steps:
      - uses: actions/checkout@v2.3.1

