name: Ubuntu

on:
  workflow_dispatch:

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - run: cat /etc/issue
      - run: uname -a


  cibtauber:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --user root --cpus=1

    steps:
      - run: uname -a
      

